user:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
helpers:
  users_helper:
    sizeofgravatar: 80
controllers:
  sessions_controller:
    remember_1: "1"
    remember_0: "0"
integration:
  users_login_test:
    remember_1: "1"
    remember_0: "0"
